# Generated by Django 2.1.10 on 2019-07-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('grade', models.IntegerField()),
                ('classes', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('classroom', models.CharField(default='0000', max_length=6)),
                ('popular', models.IntegerField(default=0)),
                ('compulsory', models.BooleanField(default=False)),
                ('credit', models.IntegerField(default=4)),
                ('popular_limit', models.IntegerField(default=60)),
                ('time', models.CharField(default='', max_length=100)),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('period', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='time',
            unique_together={('week', 'period')},
        ),
        migrations.AddField(
            model_name='coursetime',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Time'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.Teacher'),
        ),
        migrations.AddField(
            model_name='classes',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Department'),
        ),
        migrations.AlterUniqueTogether(
            name='coursetime',
            unique_together={('course', 'time')},
        ),
    ]
