# Generated by Django 2.1.10 on 2019-07-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='name',
        ),
    ]
