# Generated by Django 2.1.10 on 2019-07-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_remove_classes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
