# Generated by Django 2.1.10 on 2019-07-30 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20190729_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Course'),
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='courseteacher',
            unique_together={('course', 'teacher')},
        ),
    ]
