# Generated by Django 2.1.10 on 2019-08-02 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_auto_20190730_2102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseteacher',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='courseteacher',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseteacher',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.Teacher'),
        ),
        migrations.DeleteModel(
            name='CourseTeacher',
        ),
    ]
