# Generated by Django 2.1.10 on 2019-08-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_auto_20190802_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
